- hosts: all
  become: yes
  become_method: sudo
  vars:
    packages:
      - nodejs
      - ruby
      - nginx
  tasks:
    - name: ensure extra packages are available
      yum:
        name: epel-release
        state: present

    - name: ensure packages are installed
      yum:
        name: "{{item}}"
        state: present
      with_items: "{{packages}}"

    - name: ensure nginx is configured
      template:
        src: nginx.conf
        dest: /etc/nginx/conf.d/

    - name: ensure nginx has been restarted
      service:
        name: nginx
        state: restarted

    - name: ensure app code is on the box in /mnt
      copy:
        src: "{{item}}"
        dest: /mnt/
      with_fileglob: app.*
